# Generated by Django 2.1.5 on 2019-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190122_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email2',
            field=models.CharField(max_length=50),
        ),
    ]
