# Generated by Django 2.1.5 on 2019-01-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190122_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productImgs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='api.ProductImg'),
        ),
    ]
