# Generated by Django 2.1.5 on 2019-01-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190122_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImgs',
        ),
        migrations.AddField(
            model_name='productimg',
            name='productImgs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.Product'),
        ),
    ]
