# Generated by Django 2.1.5 on 2019-01-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190122_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimg',
            old_name='productImgs',
            new_name='product',
        ),
    ]
