# Generated by Django 2.1.5 on 2019-01-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190122_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='url',
            field=models.ImageField(upload_to='imgs/produts'),
        ),
    ]
