# Generated by Django 2.1.5 on 2019-01-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_categorytranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytranslation',
            name='product',
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
