# Generated by Django 2.1.5 on 2019-01-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190128_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Subcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.Contact'),
        ),
    ]
