# Generated by Django 2.1.5 on 2019-01-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_producttranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='quantity',
        ),
    ]
